name: RunningService server CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  S3_BUCKET_NAME: zerobase-bucket-test

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Make Directory
        run: mkdir -p deploy

      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      - name: Copy AppSpec.yaml
        run: cp AppSpec.yaml ./deploy

      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

      - name: Make zip file
        run: zip -r ./runningservicetest.zip ./deploy
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./runningservicetest.zip s3://$S3_BUCKET_NAME/

      - name: Deploy
        env:
          AWS-ACCESS-KEY-ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS-SECRET-ACCESS-KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name runningService \
          --deployment-group-name wadadakBackend \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=zerobase-bucket-test,bundleType=zip,key=runningservicetest.zip \ 
          --region ap-northeast-2 
